#!/bin/sh
imagePrefix=deploy

rm -rf ~/deploy
mkdir ~/deploy

# Stop Containers
docker stop "$imagePrefix"_rp1_1
docker stop "$imagePrefix"_fe1_1
docker stop "$imagePrefix"_fe2_1
docker stop "$imagePrefix"_fe3_1

# Remove Containers
docker rm "$imagePrefix"_rp1_1
docker rm "$imagePrefix"_fe1_1
docker rm "$imagePrefix"_fe2_1
docker rm "$imagePrefix"_fe3_1

# Remove Images
docker rmi "$imagePrefix"_rp1:latest
docker rmi "$imagePrefix"_fe1:latest
docker rmi "$imagePrefix"_fe2:latest
docker rmi "$imagePrefix"_fe3:latest
