#!/bin/sh

cd /src

# for file in /src/html/*.html ; do
# 	echo "FILE: $file"
# 	touch "$file"
# done
rm -rf /src/public/index.html
cat /src/html/indexHead.html >> /src/public/index.html
cat /src/html/headHead.html >> /src/public/index.html
for file in /src/components/*.html ; do
	cat "$file" >> /src/public/index.html
done
cat /src/html/headTail.html >> /src/public/index.html
cat /src/html/bodyHead.html >> /src/public/index.html
cat /src/html/app.html >> /src/public/index.html
cat /src/html/appjs.html >> /src/public/index.html
cat /src/html/bodyTail.html >> /src/public/index.html
cat /src/html/indexTail.html >> /src/public/index.html


case $1 in

	dev)
		rm /src/public/index.js
		touch /src/public/index.js
		echo "var environment = 'dev';" >> /src/public/index.js;
		# cd /src
		npm install
		npm start &
		ps -ef

		while inotifywait -e modify /src --recursive --exclude "npm-debug.log"; do

			rm -rf /src/public/index.html
			touch /src/public/index.html
			cat /src/html/indexHead.html >> /src/public/index.html
			cat /src/html/headHead.html >> /src/public/index.html
			for file in /src/components/*.html ; do
				cat "$file" >> /src/public/index.html
			done
			cat /src/html/headTail.html >> /src/public/index.html
			cat /src/html/bodyHead.html >> /src/public/index.html
			cat /src/html/app.html >> /src/public/index.html
			cat /src/html/appjs.html >> /src/public/index.html
			cat /src/html/bodyTail.html >> /src/public/index.html
			cat /src/html/indexTail.html >> /src/public/index.html

			killall -9 node
			npm start &
			ps ef
		done
	;;

	prod)
		rm /src/public/index.js
		touch /src/public/index.js
		echo "var environment = 'prod';" >> /src/public/index.js;
		# cd /src
		npm install
		npm start
	;;

	*)
		echo "Init Container: init [dev | prod]"

esac
